[package]
name = "linetest-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linetest = {path = "../"}
gumdrop = "0.8.0"
log = "0.4.14"
env_logger = "0.9.0"
crossterm = "0.20"